package com.example.sharedui.uiElement.style.theme

import androidx.compose.ui.graphics.Color

data class CustomTheme(
    val background: Color,
    val redDark: Color,
    val redIcon: Color,
    val darkBlue: Color,
    val blackLight: Color,
    val brownLight: Color,
    val black: Color,
    val blackFailed: Color,
    val gray: Color,
    val grayDark: Color,
    val redMedium: Color,
    val grayLight: Color,
    val grayLineLight: Color,
    val visibleGray: Color,
    val greenLight: Color,
    val hintIconBottom: Color,
    val redDarkDash: Color,
    val white: Color,
    val transparent: Color,
    val green: Color,
    val coolGray: Color,
    val redDarkTR50: Color,
    val green2BEF4A: Color,
    val grayC1C7CD: Color,
    val redDarkTR77: Color,
    val grayECECEC: Color,
    val grayD7D7D7: Color,
    val grayDark646464: Color,
    val blueLight7891B7: Color,
    val redSemiLightC66363: Color,
    val redLightDB9E9C: Color,
    val gold: Color,
    val blackTR25: Color,
    val redLightFE8499: Color,
    val binkLightFB5DAA: Color,
    val grayLightF2F2F2: Color,
    val greenMed4CAF50: Color,
    val grayDark6B6B6B: Color,
    val blue1DA1F2: Color,
    val blackTR70: Color,
    val redLightFF979B: Color,
    val redBF171DTR76: Color,
    val blackLight353535: Color,
    val black333333: Color,
    val gray939393: Color
)
